require 'pp'

lane :test1 do
  analyze_ios_linkmap(
    file_path: '/Users/xiongzenghui/Desktop/Demo-LinkMap-normal-arm64.txt'
  )

  puts '-' * 50
  # pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_JSON]
  pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_HASH]
end

lane :test2 do
  analyze_ios_linkmap(
    file_path: '/Users/xiongzenghui/Desktop/Demo-LinkMap-normal-arm64.txt',
    all_symbols: true
  )

  puts '-' * 50
  # pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_JSON]
  pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_HASH]
end

lane :test3 do
  analyze_ios_linkmap(
    file_path: '/Users/xiongzenghui/Desktop/Demo-LinkMap-normal-arm64.txt',
    merge_by_pod: true
  )

  puts '-' * 50
  # pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_MERGE_JSON]
  pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_MERGE_HASH]
end

lane :test4 do
  analyze_ios_linkmap(
    file_path: '/Users/xiongzenghui/Desktop/Demo-LinkMap-normal-arm64.txt',
    search_symbol: 'TDATEvo'
  )
  pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_SEARCH_SYMBOL]
end
