lane :test do
  analyze_ios_linkmap(
    # filepath: '/Users/xiongzenghui/Desktop/6.13.0_osee2unifiedRelease-LinkMap-normal-arm64.txt'
    filepath: '/Users/xiongzenghui/Desktop/6.13.0.1_osee2unifiedRelease-LinkMap-normal-arm64.txt'
  )
  pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_PARSED_HASH]

  # analyze_ios_linkmap(
  #   filepath: '/Users/xiongzenghui/Desktop/osee2unifiedRelease-LinkMap-normal-arm64.txt',
  #   search_symbol: 'TDATEvo'
  # )
  # pp Fastlane::Actions.lane_context[Fastlane::Actions::ShatedValues::ANALYZE_IOS_LINKMAP_SEARCH_SYMBOL]
end
